name: "Publish to Docker Registry"
description: "Build a container image and push it to the Docker registry"
branding:
  icon: image
  color: orange

inputs: 
  registry_username:
    description: "Username of the Docker registry"
    required: true
  registry_password: 
    description: "Password of the Docker registry"
    required: true
  image_name:
    description: "Name of the Docker image to push"
    required: true
  image_tag:
    description: "Tag of the Docker image. Default: Latest"

runs: 
  using: "composite"
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
